title: Festina Lente.
description: 
author: Suin Kim
avatar: /logo.jpg
email: starcat370@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Roo_star_
  card: summary
logo: logo.jpg
social:
  name: Suin Kim
  links:
    - https://twitter.com/Roo_star_
    - https://github.com/starcat37
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: kr
