title: Festina Lente.
description: 
author: Suin Kim
avatar: /logo.jpg
email: starcat37@korea.ac.kr
location: Seoul, South Korea
subscribe: false

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
 
disqus: "starcat37-github-io"

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Roo_star_
  card: summary
logo: logo.jpg
social:
  name: Suin Kim
  links:
    - https://twitter.com/Roo_star_
    - https://github.com/starcat37
lang: en

future: true